# Generated by Django 5.2.11 on 2026-02-28 03:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='brith_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
